version: 2
jobs:
  build_test:
    working_directory: /go/src/github.com/anthdm/hbbft
    docker:
      - image: vidsyhq/go-builder:latest
        environment:
          BUILD: false
    steps:
      - checkout
      - run: /scripts/build.sh
      - run: go test
workflows:
  version: 2
 build_test:
    jobs:
      - build_test:
          filters:
            tags:
              only: /[0-9]+\.[0-9]+\.[0-9]+/
            branches:
              ignore: master